/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Formularios;

import br.main.appmdi.FormPrincipal;
import javax.swing.JOptionPane;

/**
 *
 * @author sdc.daniel
 */
public class Horista extends javax.swing.JInternalFrame {

    /**
     * Creates new form Horista
     */
    public Horista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTNomeHorista = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTEnderecoHorista = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTCPFHorista = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTNumerodeHoras = new javax.swing.JTextField();
        jBSalvarHorista = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTValorHora = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setTitle("Cadastro Horista");

        jLabel1.setText("Nome:");

        jLabel2.setText("Endereço:");

        jLabel3.setText("CPF:");

        jLabel4.setText("Número de horas:");

        jBSalvarHorista.setText("Salvar");
        jBSalvarHorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarHoristaActionPerformed(evt);
            }
        });

        jLabel5.setText("Valor da hora:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTValorHora))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3))
                            .addComponent(jTCPFHorista, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(1, 1, 1))
                            .addComponent(jTNumerodeHoras)))
                    .addComponent(jTNomeHorista)
                    .addComponent(jTEnderecoHorista)
                    .addComponent(jBSalvarHorista, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTNomeHorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTEnderecoHorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCPFHorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNumerodeHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBSalvarHorista))
                    .addComponent(jTValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalvarHoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarHoristaActionPerformed
        // TODO add your handling code here:
        FormPrincipal form = new FormPrincipal();
        String nome;
        String endereco;
        String cpf;
        int nHoras;
        double vHoras;
        //Recuperando dodos da interface
        nome = jTNomeHorista.getText();
        endereco = jTEnderecoHorista.getText();
        cpf = jTCPFHorista.getText();
        nHoras = Integer.parseInt(jTNumerodeHoras.getText());
        vHoras = Double.parseDouble(jTValorHora.getText());
        form.inserirHorista(nome,endereco,cpf,nHoras,vHoras);
        JOptionPane.showMessageDialog(rootPane, "Registro realizado com sucesso");
        //Limpando os campos
        jTNomeHorista.setText("");
        jTEnderecoHorista.setText("");
        jTCPFHorista.setText("");
        jTNumerodeHoras.setText("");
        jTValorHora.setText("");
    }//GEN-LAST:event_jBSalvarHoristaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSalvarHorista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTCPFHorista;
    private javax.swing.JTextField jTEnderecoHorista;
    private javax.swing.JTextField jTNomeHorista;
    private javax.swing.JTextField jTNumerodeHoras;
    private javax.swing.JTextField jTValorHora;
    // End of variables declaration//GEN-END:variables
}
